/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Lattice" position={[0, 5.242, 0]} scale={[5.613, 4.662, 5.369]} />
        <mesh name="Base" geometry={nodes.Base.geometry} material={materials['Material.004']} position={[0, 2.731, 0]}>
          <mesh name="SnowBall003" geometry={nodes.SnowBall003.geometry} material={materials.Snow} position={[0.02, -0.252, 0.007]} />
        </mesh>
        <mesh name="Glass" geometry={nodes.Glass.geometry} material={materials.GLASS} position={[0, 6.239, 0]} scale={6.687} />
        <mesh name="Home" geometry={nodes.Home.geometry} material={nodes.Home.material} position={[0, 3.027, 0]} scale={[1, 1, 0.803]}>
          <mesh name="Fire" geometry={nodes.Fire.geometry} material={materials['Material.005']} position={[1.509, 2.456, -0.454]} scale={[0.424, 0.424, 0.528]} />
          <mesh name="Front-Back" geometry={nodes['Front-Back'].geometry} material={materials['Material.003']} position={[0, -0.139, 2]} rotation={[0, 1.571, 0]} scale={[1.246, 1, 1]} />
          <mesh name="Sides" geometry={nodes.Sides.geometry} material={materials['Material.003']} position={[2, -0.139, 0]} scale={[1, 1, 1.246]} />
          <mesh name="SnowBall001" geometry={nodes.SnowBall001.geometry} material={materials['Snow.001']} position={[-0.009, 2.521, 0.015]} scale={[1, 1, 1.246]} />
          <mesh name="SnowBall002" geometry={nodes.SnowBall002.geometry} material={materials['Snow.002']} position={[1.492, 4.129, -0.441]} scale={[1, 1, 1.246]} />
          <mesh name="Top-Front-Back" geometry={nodes['Top-Front-Back'].geometry} material={materials['Material.004']} position={[0, -0.139, 0]} />
        </mesh>
        <mesh name="Snow" geometry={nodes.Snow.geometry} material={materials['Material.002']} position={[1.372, 9.351, -2.05]} scale={0.032} />
        <mesh name="TreemedStand" geometry={nodes.TreemedStand.geometry} material={materials['Material.003']} position={[-2.512, 2.7, 4.875]} scale={0.359}>
          <mesh name="Treemed" geometry={nodes.Treemed.geometry} material={materials.Snow} rotation={[0, -0.031, 0]} />
        </mesh>
        <mesh name="TreesmallStand" geometry={nodes.TreesmallStand.geometry} material={materials['Material.003']} position={[0.729, 2.7, 4.875]} scale={0.227}>
          <mesh name="Treesmall" geometry={nodes.Treesmall.geometry} material={materials.Snow} rotation={[0, 0, 0.016]} />
        </mesh>
        <mesh name="TtreelargeStand" geometry={nodes.TtreelargeStand.geometry} material={materials['Material.003']} position={[3.575, 2.7, 1.705]} scale={0.509}>
          <mesh name="Treelarge" geometry={nodes.Treelarge.geometry} material={materials.Snow} scale={[1, 1.034, 1]} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
