/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/LAB1.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/LAB1.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[8.431, 2.426, -0.009]} scale={[5.218, 0.157, 2.606]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Material} position={[8.436, 0.885, -0.012]} rotation={[3.137, -0.728, 3.133]} scale={1.398} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Material} position={[8.436, 0.885, -0.012]} rotation={[3.138, 0.635, 3.138]} scale={1.398} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.002']} position={[8.751, 7.025, -1.038]} scale={[14.397, 7.72, 13.211]} />
      <mesh geometry={nodes.Chair_Legs.geometry} material={materials['Material.004']} position={[1.743, -0.614, -1.056]} rotation={[Math.PI, 1.555, -2.978]} scale={4.294}>
        <mesh geometry={nodes.BackRest.geometry} material={materials['Material.004']} position={[-0.143, 0.686, -0.169]} rotation={[1.209, -0.153, -0.058]} />
        <group position={[-0.347, 0.509, -0.002]} rotation={[0.208, 0.513, -0.589]}>
          <mesh geometry={nodes.Circle005.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle005_1.geometry} material={materials['screw hole']} />
        </group>
        <group position={[-0.345, 0.519, 0.141]} rotation={[0.219, 0.509, -0.611]}>
          <mesh geometry={nodes.Circle006.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle006_1.geometry} material={materials['screw hole']} />
        </group>
        <group position={[-0.306, 0.64, -0.15]} rotation={[0.983, -0.713, -0.77]}>
          <mesh geometry={nodes.Circle007.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle007_1.geometry} material={materials['screw hole']} />
        </group>
        <group position={[-0.259, 0.768, -0.198]} rotation={[1.077, -0.789, -0.597]}>
          <mesh geometry={nodes.Circle003.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle003_1.geometry} material={materials['screw hole']} />
        </group>
        <mesh geometry={nodes.Seat.geometry} material={materials['Material.004']} position={[-0.175, 0.487, 0.055]} rotation={[0, 0, -0.163]} />
        <mesh geometry={nodes.support.geometry} material={materials['Material.004']} position={[-0.197, 0.355, 0.179]} rotation={[0, 0, -0.163]} />
        <mesh geometry={nodes.support001.geometry} material={materials['Material.004']} position={[-0.2, 0.341, -0.185]} rotation={[0.147, -0.024, -0.161]} />
      </mesh>
      <mesh geometry={nodes.Chair_Legs001.geometry} material={materials['Material.004']} position={[1.743, -0.614, -1.056]} rotation={[Math.PI, 1.555, -2.978]} scale={4.294}>
        <mesh geometry={nodes.BackRest001.geometry} material={materials['Material.004']} position={[-0.143, 0.686, -0.169]} rotation={[1.209, -0.153, -0.058]} />
        <group position={[-0.347, 0.509, -0.002]} rotation={[0.208, 0.513, -0.589]}>
          <mesh geometry={nodes.Circle001.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle001_1.geometry} material={materials['screw hole']} />
        </group>
        <group position={[-0.306, 0.64, -0.15]} rotation={[0.983, -0.713, -0.77]}>
          <mesh geometry={nodes.Circle002.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle002_1.geometry} material={materials['screw hole']} />
        </group>
        <group position={[-0.259, 0.768, -0.198]} rotation={[1.077, -0.789, -0.597]}>
          <mesh geometry={nodes.Circle004.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle004_1.geometry} material={materials['screw hole']} />
        </group>
        <mesh geometry={nodes.Seat001.geometry} material={materials['Material.004']} position={[-0.175, 0.487, 0.055]} rotation={[0, 0, -0.163]} />
        <mesh geometry={nodes.support002.geometry} material={materials['Material.004']} position={[-0.2, 0.341, -0.185]} rotation={[0.147, -0.024, -0.161]} />
      </mesh>
      <mesh geometry={nodes.Chair_Legs002.geometry} material={materials['Material.004']} position={[15.508, -0.731, 1.028]} rotation={[Math.PI, -1.567, -2.978]} scale={4.294}>
        <mesh geometry={nodes.BackRest002.geometry} material={materials['Material.004']} position={[-0.143, 0.686, -0.169]} rotation={[1.209, -0.153, -0.058]} />
        <group position={[-0.347, 0.509, -0.002]} rotation={[0.208, 0.513, -0.589]}>
          <mesh geometry={nodes.Circle008.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle008_1.geometry} material={materials['screw hole']} />
        </group>
        <group position={[-0.306, 0.64, -0.15]} rotation={[0.983, -0.713, -0.77]}>
          <mesh geometry={nodes.Circle009.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle009_1.geometry} material={materials['screw hole']} />
        </group>
        <group position={[-0.259, 0.768, -0.198]} rotation={[1.077, -0.789, -0.597]}>
          <mesh geometry={nodes.Circle010.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle010_1.geometry} material={materials['screw hole']} />
        </group>
        <mesh geometry={nodes.Seat002.geometry} material={materials['Material.004']} position={[-0.175, 0.487, 0.055]} rotation={[0, 0, -0.163]} />
        <mesh geometry={nodes.support003.geometry} material={materials['Material.004']} position={[-0.2, 0.341, -0.185]} rotation={[0.147, -0.024, -0.161]} />
      </mesh>
      <mesh geometry={nodes.Chair_Legs003.geometry} material={materials['Material.004']} position={[5.823, -0.702, 4.585]} rotation={[Math.PI, 0.014, -2.978]} scale={4.294}>
        <mesh geometry={nodes.BackRest003.geometry} material={materials['Material.004']} position={[-0.143, 0.686, -0.169]} rotation={[1.209, -0.153, -0.058]} />
        <group position={[-0.347, 0.509, -0.002]} rotation={[0.208, 0.513, -0.589]}>
          <mesh geometry={nodes.Circle011.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle011_1.geometry} material={materials['screw hole']} />
        </group>
        <group position={[-0.306, 0.64, -0.15]} rotation={[0.983, -0.713, -0.77]}>
          <mesh geometry={nodes.Circle012.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle012_1.geometry} material={materials['screw hole']} />
        </group>
        <group position={[-0.259, 0.768, -0.198]} rotation={[1.077, -0.789, -0.597]}>
          <mesh geometry={nodes.Circle013.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle013_1.geometry} material={materials['screw hole']} />
        </group>
        <mesh geometry={nodes.Seat003.geometry} material={materials['Material.004']} position={[-0.175, 0.487, 0.055]} rotation={[0, 0, -0.163]} />
        <mesh geometry={nodes.support004.geometry} material={materials['Material.004']} position={[-0.2, 0.341, -0.185]} rotation={[0.147, -0.024, -0.161]} />
      </mesh>
      <mesh geometry={nodes.Chair_Legs004.geometry} material={materials['Material.004']} position={[9.164, -0.702, 4.617]} rotation={[Math.PI, -0.041, -2.978]} scale={4.294}>
        <mesh geometry={nodes.BackRest004.geometry} material={materials['Material.004']} position={[-0.143, 0.686, -0.169]} rotation={[1.209, -0.153, -0.058]} />
        <group position={[-0.347, 0.509, -0.002]} rotation={[0.208, 0.513, -0.589]}>
          <mesh geometry={nodes.Circle014.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle014_1.geometry} material={materials['screw hole']} />
        </group>
        <group position={[-0.306, 0.64, -0.15]} rotation={[0.983, -0.713, -0.77]}>
          <mesh geometry={nodes.Circle015.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle015_1.geometry} material={materials['screw hole']} />
        </group>
        <group position={[-0.259, 0.768, -0.198]} rotation={[1.077, -0.789, -0.597]}>
          <mesh geometry={nodes.Circle016.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle016_1.geometry} material={materials['screw hole']} />
        </group>
        <mesh geometry={nodes.Seat004.geometry} material={materials['Material.004']} position={[-0.175, 0.487, 0.055]} rotation={[0, 0, -0.163]} />
        <mesh geometry={nodes.support005.geometry} material={materials['Material.004']} position={[-0.2, 0.341, -0.185]} rotation={[0.147, -0.024, -0.161]} />
      </mesh>
      <mesh geometry={nodes.Chair_Legs005.geometry} material={materials['Material.004']} position={[11.122, -0.762, -5.094]} rotation={[0, -0.059, 0.163]} scale={4.294}>
        <mesh geometry={nodes.BackRest005.geometry} material={materials['Material.004']} position={[-0.143, 0.686, -0.169]} rotation={[1.209, -0.153, -0.058]} />
        <group position={[-0.347, 0.509, -0.002]} rotation={[0.208, 0.513, -0.589]}>
          <mesh geometry={nodes.Circle017.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle017_1.geometry} material={materials['screw hole']} />
        </group>
        <group position={[-0.306, 0.64, -0.15]} rotation={[0.983, -0.713, -0.77]}>
          <mesh geometry={nodes.Circle018.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle018_1.geometry} material={materials['screw hole']} />
        </group>
        <group position={[-0.259, 0.768, -0.198]} rotation={[1.077, -0.789, -0.597]}>
          <mesh geometry={nodes.Circle019.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle019_1.geometry} material={materials['screw hole']} />
        </group>
        <mesh geometry={nodes.Seat005.geometry} material={materials['Material.004']} position={[-0.175, 0.487, 0.055]} rotation={[0, 0, -0.163]} />
        <mesh geometry={nodes.support006.geometry} material={materials['Material.004']} position={[-0.2, 0.341, -0.185]} rotation={[0.147, -0.024, -0.161]} />
      </mesh>
      <mesh geometry={nodes.Chair_Legs006.geometry} material={materials['Material.004']} position={[7.786, -0.762, -5.277]} rotation={[0, -0.005, 0.163]} scale={4.294}>
        <mesh geometry={nodes.BackRest006.geometry} material={materials['Material.004']} position={[-0.143, 0.686, -0.169]} rotation={[1.209, -0.153, -0.058]} />
        <group position={[-0.347, 0.509, -0.002]} rotation={[0.208, 0.513, -0.589]}>
          <mesh geometry={nodes.Circle020.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle020_1.geometry} material={materials['screw hole']} />
        </group>
        <group position={[-0.306, 0.64, -0.15]} rotation={[0.983, -0.713, -0.77]}>
          <mesh geometry={nodes.Circle021.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle021_1.geometry} material={materials['screw hole']} />
        </group>
        <group position={[-0.259, 0.768, -0.198]} rotation={[1.077, -0.789, -0.597]}>
          <mesh geometry={nodes.Circle022.geometry} material={materials.screw} />
          <mesh geometry={nodes.Circle022_1.geometry} material={materials['screw hole']} />
        </group>
        <mesh geometry={nodes.Seat006.geometry} material={materials['Material.004']} position={[-0.175, 0.487, 0.055]} rotation={[0, 0, -0.163]} />
        <mesh geometry={nodes.support007.geometry} material={materials['Material.004']} position={[-0.2, 0.341, -0.185]} rotation={[0.147, -0.024, -0.161]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/LAB1.gltf')
