import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Nav'
import { connect } from "@/dbConfig/dbConfig"

const inter = Inter({ subsets: ['latin'] })
connect()

export const metadata = {
  title: 'Houssem DH Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
      <Navbar/>
        {children}
        
        </body>
    </html>
  )
}
