/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 LAB1.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/LAB1.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Background.geometry} material={materials['Material.002']} position={[8.751, 7.025, -1.038]} scale={[281.87, 7.72, 112.255]} />
      <mesh geometry={nodes.Table.geometry} material={materials['Wood Black UA']} position={[8.431, 2.266, -0.009]} scale={[5.218, 0.157, 2.606]} />
      <mesh geometry={nodes.Chair3.geometry} material={materials.Wood} position={[7.786, -0.68, -5.277]} rotation={[0, -0.005, 0.163]} scale={4.294} />
      <mesh geometry={nodes.Chair2.geometry} material={materials.Wood} position={[11.554, -0.68, -5.277]} rotation={[0, -0.005, 0.163]} scale={4.294} />
      <mesh geometry={nodes.Chair6.geometry} material={materials.Wood} position={[9.374, -0.68, 5.086]} rotation={[Math.PI, 0.014, -2.978]} scale={4.294} />
      <mesh geometry={nodes.Chair5.geometry} material={materials.Wood} position={[5.607, -0.68, 5.049]} rotation={[Math.PI, 0.014, -2.978]} scale={4.294} />
      <mesh geometry={nodes.Chair4.geometry} material={materials.Wood} position={[2.314, -0.68, -1.134]} rotation={[-Math.PI, 1.569, -2.978]} scale={4.294} />
      <mesh geometry={nodes.Chair1.geometry} material={materials.Wood} position={[14.626, -0.68, 1.056]} rotation={[Math.PI, -1.562, -2.978]} scale={4.294} />
    </group>
  )
}

useGLTF.preload('/LAB1.gltf')
